#!/usr/bin/env bash
# Regenerates the design-sync compiled stylesheet from the decimal source files.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=frontend/src/styles/decimal/ds-sync-entry.css
{
  echo "/* GENERATED by .design-sync/build-css.sh — do not edit. Source: tokens.css + components.css + pages.css */"
  echo "@import url('https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,300;12..96,400;12..96,500;12..96,600;12..96,700&family=JetBrains+Mono:wght@400;500;600&display=swap');"
  cat frontend/src/styles/decimal/tokens.css frontend/src/styles/decimal/components.css frontend/src/styles/decimal/pages.css
} > "$OUT"
echo "wrote $OUT ($(du -h "$OUT" | cut -f1))"
