import { Router } from 'express';
import { config } from '../config.js';
import { USDC_MINT } from '../solana.js';

export const capabilitiesRouter = Router();

capabilitiesRouter.get('/capabilities', (_req, res) => {
  res.json({
    product: 'decimal',
    version: 1,
    generatedAt: new Date().toISOString(),
    solana: {
      network: config.solanaNetwork,
      usdcMint: USDC_MINT.toBase58(),
      rpcUrl: config.solanaRpcUrl,
    },
    auth: {
      user: 'Authorization: Bearer <sessionToken>',
    },
    onboarding: {
      autoProvisionWallets: config.autoProvisionWallets,
      managedWalletProvider: config.privyAppId && config.privyAppSecret ? 'privy' : null,
      devnetAutoFundWallets: config.devnetAutoFundWallets,
      devnetAutoFundLamports: config.devnetAutoFundWallets ? config.devnetAutoFundLamports : null,
      organizationCreateProvisions: ['owner_personal_wallet', 'default_automation_agent_wallet'],
      inviteAcceptProvisions: ['member_personal_wallet'],
    },
    providers: {
      squads: {
        mode: 'direct',
        programId: config.squadsProgramId,
      },
    },
    apiSurface: {
      style: 'resource-oriented-json',
      openApi: 'GET /openapi.json returns the machine-readable OpenAPI 3.1 contract.',
      idempotency: 'Send Idempotency-Key on mutating requests that may be retried.',
      requestTracing: 'Every response includes x-request-id. Clients may provide x-request-id for trace correlation.',
      errors: {
        shape: {
          error: 'string',
          message: 'string',
          code: 'string',
          requestId: 'string',
        },
      },
    },
    workflows: [
      {
        id: 'invoice_to_payment_order',
        summary: 'Upload an invoice, let AP intake create payment orders, let the Decimal agent create Squads proposals for green rows, clear any needs-review item, execute approved proposals, verify settlement by RPC, then export proof.',
        steps: [
          'POST /organizations/:organizationId/invoices/upload with autoAdvance=true',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/clear-review with autoAdvance=true when review is required',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/agent/advance for idempotent retry/manual agent advance',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/approve-intent for human Squads votes',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/execute-intent once threshold is met',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-execution',
          'GET /organizations/:organizationId/payment-orders/:paymentOrderId/proof',
        ],
      },
      {
        id: 'single_payment',
        summary: 'Create one payment order, let the Decimal agent create a Squads proposal, execute it, verify settlement by RPC, then export proof.',
        steps: [
          'POST /organizations/:organizationId/payment-orders with submitNow=true',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/agent/advance for idempotent retry/manual agent advance',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-submission',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-execution',
          'GET /organizations/:organizationId/payment-orders/:paymentOrderId/proof',
        ],
      },
      {
        id: 'csv_to_payment_orders',
        summary: 'Preview CSV rows, import payment orders with a shared input batch label, optionally create one Squads proposal for selected rows, execute it, verify settlement by RPC, then export proof.',
        steps: [
          'POST /organizations/:organizationId/payment-orders/batch-csv/preview',
          'POST /organizations/:organizationId/payment-orders/batch-csv',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/vault-proposals/payment-batch-intent',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-submission',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-execution',
          'GET /organizations/:organizationId/payment-orders/:paymentOrderId/proof for each row',
        ],
      },
      {
        id: 'collections',
        summary: 'Create expected inbound collections or import a receivables CSV. Collections are currently intent records; automatic inbound chain watching is intentionally detached from the lean MVP.',
        steps: [
          'POST /organizations/:organizationId/collections',
          'POST /organizations/:organizationId/collection-runs/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv',
          'GET /organizations/:organizationId/collections/:collectionRequestId',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId',
          'GET /organizations/:organizationId/collections/:collectionRequestId/proof',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId/proof',
        ],
      },
      {
        id: 'agent_spending_limit_execution',
        summary: 'Create an automation agent, give its managed wallet initiate-only Squads membership, add a Squads spending limit, sync it active, then let the agent execute bounded payments without proposal voting.',
        steps: [
          'POST /organizations/:organizationId/automation-agents',
          'POST /organizations/:organizationId/automation-agents/:automationAgentId/wallets/managed',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/add-agent-member-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/add-spending-limit-intent',
          'POST /organizations/:organizationId/spending-limit-policies/:spendingLimitPolicyId/sync',
          'POST /organizations/:organizationId/spending-limit-policies/:spendingLimitPolicyId/replace-intent',
          'POST /organizations/:organizationId/spending-limit-policies/:spendingLimitPolicyId/remove-intent',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/execute-with-spending-limit',
          'GET /organizations/:organizationId/spending-limit-executions',
        ],
      },
    ],
    endpointGroups: [
      {
        group: 'setup',
        routes: [
          'POST /auth/register',
          'POST /auth/login',
          'GET /auth/session',
          'POST /auth/verify-email',
          'GET /openapi.json',
          'GET /invites/:inviteToken',
          'GET /organizations',
          'POST /organizations',
          'GET /organizations/:organizationId/members',
          'GET /organizations/:organizationId/invites',
          'POST /organizations/:organizationId/invites',
          'POST /organizations/:organizationId/invites/:organizationInviteId/revoke',
          'POST /invites/:inviteToken/accept',
          'GET /personal-wallets',
          'POST /personal-wallets/managed',
          'DELETE /personal-wallets/:userWalletId',
          'POST /personal-wallets/:userWalletId/sign-versioned-transaction',
          'GET /organizations/:organizationId/treasury-wallets',
          'POST /organizations/:organizationId/treasury-wallets/squads/create-intent',
          'POST /organizations/:organizationId/treasury-wallets/squads/confirm',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/detail',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/status',
          'GET /organizations/:organizationId/squads/proposals',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/:transactionIndex',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/add-member-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/change-threshold-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/vault-proposals/payment-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/vault-proposals/payment-batch-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/:transactionIndex/approve-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/:transactionIndex/execute-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/sync-members',
          'GET /organizations/:organizationId/proposals',
          'GET /organizations/:organizationId/proposals/:decimalProposalId',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-submission',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-execution',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/approve-intent',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/execute-intent',
          'GET /organizations/:organizationId/wallet-authorizations',
          'POST /organizations/:organizationId/wallet-authorizations',
          'GET /organizations/:organizationId/counterparty-wallets',
          'GET /organizations/:organizationId/automation-agents',
          'POST /organizations/:organizationId/automation-agents',
          'GET /organizations/:organizationId/agent-wallets',
          'POST /organizations/:organizationId/automation-agents/:automationAgentId/wallets/managed',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/add-agent-member-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/add-spending-limit-intent',
          'GET /organizations/:organizationId/spending-limit-policies',
          'GET /organizations/:organizationId/spending-limit-policies/:spendingLimitPolicyId',
          'POST /organizations/:organizationId/spending-limit-policies/:spendingLimitPolicyId/sync',
          'POST /organizations/:organizationId/spending-limit-policies/:spendingLimitPolicyId/replace-intent',
          'POST /organizations/:organizationId/spending-limit-policies/:spendingLimitPolicyId/remove-intent',
          'GET /organizations/:organizationId/spending-limit-policies/:spendingLimitPolicyId/executions',
          'GET /organizations/:organizationId/spending-limit-executions',
        ],
      },
      {
        group: 'input',
        routes: [
          'POST /organizations/:organizationId/payment-orders',
          'POST /organizations/:organizationId/payment-orders/batch-csv/preview',
          'POST /organizations/:organizationId/payment-orders/batch-csv',
          'POST /organizations/:organizationId/invoices/upload',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/agent/advance',
          'POST /organizations/:organizationId/collections',
          'POST /organizations/:organizationId/collections/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv',
          'POST /organizations/:organizationId/counterparty-wallets',
        ],
      },
      {
        group: 'control_and_execution',
        routes: [
          'GET /organizations/:organizationId/payment-orders',
          'POST /organizations/:organizationId/payment-orders',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/submit',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/clear-review',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/agent/advance',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/prepare-execution',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/attach-signature',
          'POST /organizations/:organizationId/collections/:collectionRequestId/cancel',
          'PATCH /organizations/:organizationId/counterparty-wallets/:counterpartyWalletId',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/execute-with-spending-limit',
          'GET /organizations/:organizationId/spending-limit-executions',
        ],
      },
      {
        group: 'verification_and_proof',
        routes: [
          'GET /organizations/:organizationId/payment-orders/:paymentOrderId/proof',
          'GET /organizations/:organizationId/collections',
          'GET /organizations/:organizationId/collections/:collectionRequestId',
          'GET /organizations/:organizationId/collections/:collectionRequestId/proof',
          'GET /organizations/:organizationId/collection-runs',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId/proof',
          'GET /organizations/:organizationId/audit-log',
          'GET /organizations/:organizationId/ops-health',
        ],
      },
    ],
    safetyNotes: [
      'The API never accepts or stores private keys.',
      'Prepared Squads transactions are signed by user-controlled personal wallets through the wallet/Privy flow.',
      'Green AP intake rows can be proposed by the backend-managed org agent wallet, but execution still follows Squads voting unless a spending limit is explicitly active.',
      'Submitted signatures are verified by Solana RPC before being stored as proposal evidence.',
      'Payment settlement is verified from RPC transaction token-account deltas.',
    ],
  });
});
